install: gradle wrapper --gradle-version 4.6
language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: PaaiUBxwxxLggbrhXYQvleTh+pAHt/xh7l2rysxWiVVWIUeSqWeTY/4dkUgXqVIVxid5kgPLCnJFSs8tmIEkBxJhMsfRm/gYEJTNDYkXBaplrTlp43rIEjstXmM4832sf7oaYgPqbzTvBxF1UEZWoNb0lmao3eFjMCGpXrRirccDm/motXYcRhc19aq4kL0doHvFxTo88xwBbWaj2Qklm6x1rOu34g7H9C/eWkVzTPfTfdjpksAl0TTOXhc9CtqJDQpStzHf2AUql1gVY4qVmLobWn6Q50pPN20J5LoluCcWvW92u+vnLuQAFsRhItBzdEvylz/SrvG+KD0jUkEFBgTkt76TkbaBoFi2rRjcW3bXE/sDjW63oHe4MSGhmmv3nZDpN8KtcaaSTEXLc/qiJKESiumTxpzkMHhRg/iqcH7Mxqr37p9rM5HjXJhDN4xQGFRjc2vkMmpEU/m7jJikn8HuZfplpfA5uNiufNAATieM5/xzE9w/Ul6OJ6M/8qlFQtAnaihkuZiCT3tbc/kNzp87SHIa4SSm3IWqug0nSFJXpXRp5SpKmy307Q1t2/+gqd4bx5w8JMGTJccE8KzMSqltl/sK9hYueIcHV73Yb832PRkDaqxTHubRZ7YNrT+AZJh/9c9C1fTbPMyTb4piQnjIbYgBYGmzyM9Fws0GHr4=
  file:
    - build/libs/NoteBlockAPI-Sponge-1.9.0-Sponge.jar
    - build/libs/NoteBlockAPI-Sponge-1.9.0-Sponge-javadoc.jar
    - build/libs/NoteBlockAPI-Sponge-1.9.0-Sponge-sources.jar
  on:
    repo: Sansko1337/NoteBlockAPI-Sponge
